/*Q1 — Customer Revenue
Calculate completed revenue for each customer.
Return:
customer_name
completed_revenue

Requirements:
Only Completed orders
Include customers with no completed orders
Show 0 for customers with no completed revenue
Sort by completed_revenue descending

After writing the SQL, explain:
Why you chose the join type
Where you applied the status filter
Why GROUP BY is required
Why COALESCE() is used*/
select c.customer_id,c.customer_name,COALESCE(sum(o.amount), 0) AS completed_revenue
from customers c left join orders o 
on c.customer_id=o.customer_id
AND o.status = 'Completed'
group by c.customer_id,c.customer_name;

/* we choose Left join to show customers even with no completed orders, filtered rows where status was'Completed' as we needed rows
for completed orders, group by is not required to aggregate data per customer, COALESCE is used to replace null values with 
0 if any such customers exists.*/

/*Q2 — Product Performance
Calculate the performance of each product based on completed orders.
Return:
•	product_name 
•	completed_orders 
•	completed_revenue 
Requirements:
•	Only completed orders 
•	Include products with no completed orders 
•	Sort by completed_revenue descending 
After writing the SQL, explain:
•	How the tables are connected 
•	How the completed-order filter works 
•	How the two metrics are calculated 
•	Why products without orders should still appear */
select p.product_name, count(o.product_id) as completed_orders,
coalesce(sum(o.amount),0) as completed_revenue
from products p left join orders o 
on p.product_id=o.product_id
and o.status='Completed'
group by p.product_id,p.product_name
order by completed_revenue desc; 
/* tables are connected vua a left join coz we need to include products with no completed orders 
using o.status completed orders are filtered out
count functions helps us to calulate the no of orders, sum to calculate the revenue of the filtered rows
products without orders should still appear so that we can get which products are not being ordered, then take business action accordingly

/*Q3 — City Revenue Analysis
Find the total completed revenue and completed orders generated by each customer city.
Return:
•	city 
•	completed_revenue 
•	completed_orders 
Requirements:
•	Only completed orders 
•	Sort by completed_revenue descending 
After writing the SQL, explain:
•	How individual orders are converted into city-level metrics 
•	Why GROUP BY city is necessary 
•	How the query calculates both revenue and order count*/
select city, coalesce(sum(o.amount),0) as completed_revenue,
count(o.order_id) as total_orders
from customers c left join orders o 
on c.customer_id=o.customer_id
and o.status='Completed'
group by c.city
order by completed_revenue desc;

/* individual orders are converted into city-level metrics  by grouping rows by city, 
it tells us city wise performance, count and sum are use to calculate the required metrics after being filtered*/


/*Q4 — Cancellation Rate by City
Calculate the cancellation rate for each city.
Return:
•	city 
•	total_orders 
•	cancelled_orders 
•	cancellation_rate 
Use:
Cancellation Rate = Cancelled Orders / Total Orders × 100
Requirements:
•	Include cities with orders 
•	Sort by cancellation_rate descending 
After writing the SQL, explain:
•	How you calculate total orders 
•	How you calculate cancelled orders 
•	Why total orders are the denominator 
•	What a high cancellation rate tells an analyst*/

select c.city,count(o.order_id) as total_orders,
sum(case when o.status='Cancelled' then 1 else 0 end) as cancelled_orders,
sum(case when o.status='Cancelled' then 1 else 0 end)/count(o.order_id) *100 as cancellation_rate
from customers c inner join orders o 
on c.customer_id=o.customer_id
group by c.city
order by cancellation_rate desc;
/* count(o.order_id) is used to calculate the total orders
	using case and applying condition as cancelled we calculated no. of cancelled orders
    total orders are the denominator because we need to calculate %, any no/total is the way to calculate %
    high cancellation rates tells analysts which cities are prone to high cancellation and take the appropriate business action*/
    
/*Q5 — Customer Order Behavior
For every customer, calculate:
•	customer_name 
•	total_orders 
•	completed_orders 
•	cancelled_orders 
•	total_revenue 
Requirements:
•	Revenue should come only from completed orders 
•	Include customers with no orders 
•	Sort by total_revenue descending 
After writing the SQL, explain:
•	How multiple metrics are calculated from the same order table 
•	How you prevent cancelled orders from contributing to revenue 
•	How customers with no orders are retained 
•	Why this query is useful for customer analysis*/

select c.customer_name,count(o.order_id) as total_orders,
sum(case when o.status='Cancelled' then 1 else 0 end) as cancelled_orders,
sum(case when o.status='Completed' then 1 else 0 end) as completed_orders,
sum(case when o.status='Completed' then o.amount else 0 end) as completed_revenue
from customers c left join orders o 
on c.customer_id=o.customer_id
group by c.customer_id,c.customer_name
order by completed_revenue desc;
/* count(o.order_id) for total orders, case with appropriate conditions for other metrics,
customers with no orders are retained by using a left join
this query is useful for customer analysis, like customer behaviuor, total conversion, serious buyers etc*/

/*Q6 — Product Cancellation Analysis
Analyze cancellation behavior for every product.
Return:
•	product_name 
•	total_orders 
•	cancelled_orders 
•	cancellation_rate 
Requirements:
•	Include products with orders 
•	Sort by cancellation_rate descending 
After writing the SQL, explain:
•	How you calculate the cancellation rate 
•	Why cancellation rate is more informative than cancellation count alone 
•	What a product with a high cancellation rate might indicate 
•	How you would use this result for business investigation*/
select p.product_name, count(p.product_id) as total_orders,
sum(case when o.status='Cancelled' then 1 else 0 end) as cancelled_orders,
sum(case when o.status='Cancelled' then 1 else 0 end)/count(p.product_id)*100 as cancellation_rate
from products p  inner join orders o 
on p.product_id=o.product_id
group by p.product_id,p.product_name
order by cancellation_rate desc;
/* cancellation rate= cancelled order/ total order * 100,
cancellation rate gives a better idea in terms of %, What proportion of placed orders were cancelled.,
we can categorize the customer as serious buyer or not, or level of commitment etc. 
high cancellation rate tells a lot, it might me about customer behaviuor, or the frictions they might be facing somewhere in the funnel,
maybe not completely trusting the brand, low confidence in the product etc. 
 